name: Build and push image

on:
  push:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build-and-publish-head:
    name: Build and publish head
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v2.5.0 # Checking out the repo

      - name: Build and publish Docker Images to GitHub Container registry
        # You may pin to the exact commit or the version.
        # uses: VaultVulp/gp-docker-action@32d98d2f1c7deb6927918b019d278a9a24aca736
        uses: VaultVulp/gp-docker-action@1.5.0
        with:
          # GitHub token to push Docker image to GitHub Packages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Docker Image name
          image-name: gitpod-terraform
          additional-image-tags: $(date '+%Y-%m-%d') ${{ github.sha }}
          

